[package]
name = "ori3-propose"
version.workspace = true
edition.workspace = true

[dependencies]
glam.workspace = true
ori3-cp.workspace = true
ori3-layers.workspace = true
ori3-model.workspace = true
ori3-rigid.workspace = true
rand.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
